# config.py
import pytz

KST = pytz.timezone("Asia/Seoul")

# ── KOSPI 워치리스트 ────────────────────────────────────────────────────────
KOSPI_WATCHLIST = {
    "005930": "삼성전자",
    "000660": "SK하이닉스",
    "402340": "SK스퀘어",
    "005935": "삼성전자우",
    "009150": "삼성전기",
    "005380": "현대차",
    "373220": "LG에너지솔루션",
    "032830": "삼성생명",
    "028260": "삼성물산",
    "207940": "삼성바이오로직스",
    "329180": "HD현대중공업",
    "034730": "SK",
    "034020": "두산에너빌리티",
    "000270": "기아",
    "105560": "KB금융",
    "012450": "한화에어로스페이스",
    "055550": "신한지주",
    "012330": "현대모비스",
    "006400": "삼성SDI",
    "068270": "셀트리온",
    "010120": "LS ELECTRIC",
    "267260": "HD현대일렉트릭",
    "035420": "NAVER",
    "042660": "한화오션",
    "066570": "LG전자",
    "086790": "하나금융지주",
    "298040": "효성중공업",
    "000810": "삼성화재",
    "005490": "POSCO홀딩스",
    "009540": "HD한국조선해양",
    "042700": "한미반도체",
    "015760": "한국전력",
    "006800": "미래에셋증권",
    "000150": "두산",
    "010130": "고려아연",
    "011070": "LG이노텍",
    "316140": "우리금융지주",
    "051910": "LG화학",
    "010140": "삼성중공업",
    "064350": "현대로템",
    "017670": "SK텔레콤",
    "011200": "HMM",
    "033780": "KT&G",
    "138040": "메리츠금융지주",
    "096770": "SK이노베이션",
    "003670": "포스코퓨처엠",
    "079550": "LIG디펜스앤에어로스페이스",
    "024110": "기업은행",
    "267250": "HD현대",
    "035720": "카카오",
    "018260": "삼성에스디에스",
    "003550": "LG",
    "047810": "한국항공우주",
    "307950": "현대오토에버",
    "272210": "한화시스템",
    "278470": "에이피알",
    "086280": "현대글로비스",
    "030200": "KT",
    "000720": "현대건설",
    "071050": "한국금융지주",
    "010950": "S-Oil",
    "006260": "LS",
    "003490": "대한항공",
    "005940": "NH투자증권",
    "259960": "크래프톤",
    "443060": "HD현대마린솔루션",
    "323410": "카카오뱅크",
    "016360": "삼성증권",
    "028050": "삼성E&A",
    "047050": "포스코인터내셔널",
    "003230": "삼양식품",
    "005830": "DB손해보험",
    "039490": "키움증권",
    "352820": "하이브",
    "047040": "대우건설",
    "161390": "한국타이어앤테크놀로지",
    "007660": "이수페타시스",
    "180640": "한진칼",
    "064400": "LG씨엔에스",
    "005387": "현대차2우B",
    "000880": "한화",
    "326030": "SK바이오팜",
    "004170": "신세계",
    "001440": "대한전선",
    "062040": "산일전기",
    "090430": "아모레퍼시픽",
    "353200": "대덕전자",
    "021240": "코웨이",
    "000990": "DB하이텍",
    "078930": "GS",
    "032640": "LG유플러스",
    "241560": "두산밥캣",
    "009830": "한화솔루션",
    "034220": "LG디스플레이",
    "454910": "두산로보틱스",
    "000100": "유한양행",
    "267270": "HD건설기계",
    "000500": "가온전선",
    "036570": "NC",
}

# ── S&P 500 Top 50 ──────────────────────────────────────────────────────────
SP500_TOP50 = {
    "AAPL":  "Apple",
    "MSFT":  "Microsoft",
    "NVDA":  "NVIDIA",
    "AMZN":  "Amazon",
    "GOOGL": "Alphabet A",
    "META":  "Meta",
    "BRK-B": "Berkshire Hathaway",
    "LLY":   "Eli Lilly",
    "AVGO":  "Broadcom",
    "TSLA":  "Tesla",
    "JPM":   "JPMorgan Chase",
    "WMT":   "Walmart",
    "V":     "Visa",
    "UNH":   "UnitedHealth",
    "XOM":   "ExxonMobil",
    "ORCL":  "Oracle",
    "MA":    "Mastercard",
    "COST":  "Costco",
    "HD":    "Home Depot",
    "PG":    "Procter & Gamble",
    "JNJ":   "Johnson & Johnson",
    "ABBV":  "AbbVie",
    "BAC":   "Bank of America",
    "KO":    "Coca-Cola",
    "NFLX":  "Netflix",
    "CRM":   "Salesforce",
    "CVX":   "Chevron",
    "MRK":   "Merck",
    "AMD":   "AMD",
    "ACN":   "Accenture",
    "PEP":   "PepsiCo",
    "TMO":   "Thermo Fisher",
    "LIN":   "Linde",
    "MCD":   "McDonald's",
    "CSCO":  "Cisco",
    "ABT":   "Abbott",
    "GE":    "GE Aerospace",
    "IBM":   "IBM",
    "TXN":   "Texas Instruments",
    "INTU":  "Intuit",
    "AMGN":  "Amgen",
    "PM":    "Philip Morris",
    "RTX":   "RTX Corp",
    "SPGI":  "S&P Global",
    "GS":    "Goldman Sachs",
    "CAT":   "Caterpillar",
    "NOW":   "ServiceNow",
    "BKNG":  "Booking Holdings",
    "DHR":   "Danaher",
    "BLK":   "BlackRock",
}

# ── NASDAQ Top 50 (SP500 미포함) ─────────────────────────────────────────────
NASDAQ_TOP50 = {
    "ADBE":  "Adobe",
    "QCOM":  "Qualcomm",
    "AMAT":  "Applied Materials",
    "MU":    "Micron",
    "LRCX":  "Lam Research",
    "KLAC":  "KLA Corp",
    "SNPS":  "Synopsys",
    "CDNS":  "Cadence Design",
    "MRVL":  "Marvell Tech",
    "FTNT":  "Fortinet",
    "PANW":  "Palo Alto Networks",
    "CRWD":  "CrowdStrike",
    "SNOW":  "Snowflake",
    "DDOG":  "Datadog",
    "ZS":    "Zscaler",
    "WDAY":  "Workday",
    "TEAM":  "Atlassian",
    "MELI":  "MercadoLibre",
    "ASML":  "ASML",
    "AZN":   "AstraZeneca",
    "GILD":  "Gilead Sciences",
    "VRTX":  "Vertex Pharma",
    "REGN":  "Regeneron",
    "BIIB":  "Biogen",
    "IDXX":  "IDEXX Labs",
    "ILMN":  "Illumina",
    "ALGN":  "Align Technology",
    "DXCM":  "DexCom",
    
    
    "TTD":   "The Trade Desk",
    "ROKU":  "Roku",
    "ZM":    "Zoom",
    "DOCU":  "DocuSign",
    "PTON":  "Peloton",
    "LYFT":  "Lyft",
    "UBER":  "Uber",
    "ABNB":  "Airbnb",
    "DASH":  "DoorDash",
    "COIN":  "Coinbase",
    "HOOD":  "Robinhood",
    "RBLX":  "Roblox",
    "U":     "Unity Software",
    "PATH":  "UiPath",
    "AI":    "C3.ai",
    "PLTR":  "Palantir",
    "SOFI":  "SoFi Technologies",
    "AFRM":  "Affirm",
    "LCID":  "Lucid Motors",
    "RIVN":  "Rivian",
}

# ── ETF (매크로 참조용) ──────────────────────────────────────────────────────
ETF_WATCHLIST = {
    "SPY":  "S&P500 ETF",
    "QQQ":  "NASDAQ ETF",
    "SOXL": "반도체 3x ETF",
    "TLT":  "미국장기채 ETF",
}

# ── 전체 통합 ────────────────────────────────────────────────────────────────
WATCHLIST = {**KOSPI_WATCHLIST, **SP500_TOP50, **NASDAQ_TOP50, **ETF_WATCHLIST}

KRX_TICKERS = [t for t in WATCHLIST if t.isdigit()]
YF_TICKERS  = [t for t in WATCHLIST if not t.isdigit()]

# ── Signal weights ───────────────────────────────────────────────────────────
WEIGHTS = {
    "macro":         0.25,
    "fundamental":         0.2,
    "supply_demand":         0.2,
    "technical":         0.2,
    "momentum":         0.15,
}

# ── Signal thresholds ────────────────────────────────────────────────────────
SIGNAL_BANDS = [
    (78, 100, "STRONG BUY"),
    (63,  78, "BUY"),
    (35,  63, "HOLD"),
    (20,  35, "SELL"),
    (  0, 20, "STRONG SELL"),
]

CONFIDENCE_BANDS = [
    (70, "HIGH"),
    (45, "MEDIUM"),
    (0,  "LOW"),
]

# ── GitHub ───────────────────────────────────────────────────────────────────
GITHUB_REPO   = "jacob-ygm/krx-dashboard"
GITHUB_BRANCH = "main"
DATA_FILE     = "data/signals_latest.csv.gz"

# ── Macro tickers (yfinance) ─────────────────────────────────────────────────
MACRO_YF = {
    "^GSPC":   "S&P500",
    "^IXIC":   "NASDAQ",
    "^VIX":    "VIX",
    "DX-Y.NYB":"DXY",
    "CL=F":    "WTI",
    "HG=F":    "Copper",
    "^KS11":   "KOSPI",
    "^KQ11":   "KOSDAQ",
    "KRW=X":   "USD/KRW",
}
